baseurl = "https://example.com/"
title = "Constant Theme Demo"
theme = "hugo-theme-constant"
languageCode = "en-us"
copyright = "Copyright © 2024 Albert Author."

[params]
  # Cutting off the page title to two chars for mobile (Constant Theme Demo -> Co)
  titleCutting = false

  # Show a small logo at footer
  # To change the logo, please name the image file "logo.png" and put it under assets/images/
  footerImg = false

  # Show favicon
  # To change the icon, please convert the icon to "favicon.ico" and put it under assets/images/
  favicon = false

  [[params.navlinks]]
  name = "Alpha"
  url = "categories/alpha/"
  
  [[params.navlinks]]
  name = "Bravo"
  url = "categories/bravo/"
  
  [[params.navlinks]]
  name = "Charlie"
  url = "categories/charlie/"
  
  [[params.navlinks]]
  name = "Delta"
  url = "categories/delta/"
  
  [[params.navlinks]]
  name = "Echo"
  url = "categories/echo/"
